import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ConnectWallet from "../components/ConnectWallet";
import DropDown from "../components/DropDown";
import MainCard from "../components/MainCard";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex items-center justify-between flex-wrap p-6">
        <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
          <div className="text-sm lg:flex-grow"></div>

          <ConnectWallet />
        </div>
      </nav>

      <main className="min-h-screen flex flex-col items-center justify-center">
        <h1 className="text-3xl">Transfer NFTs</h1>

        <p className="text-lg">Between Core and eSpace</p>
        <MainCard />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
